### ISSUE TITLE
Get TypeError when BackgroundJob run.

### ISSUE THREAD

**Issue by louis378** [nextcloud/files_antivirus#154] opened 2020-05-26 02:58 UTC
### Steps to reproduce
1.Install the app
2.wait for the next corn.php run

### Expected behaviour
Not get error in the log.

### Actual behaviour
When the BackgroundJob run, it always get the TypeError in the log.

### Server configuration

**Operating system**: Linux ubuntu 4.4.0-142-generic

**Web server:**  Apache/2.4.18 (Ubuntu)

**Database:** MySQL

**PHP version:** PHP Version 7.0.33

**Nextcloud version:** 15.0.7

**Where did you install Nextcloud from:** GitHub

**List of activated apps:**
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_antivirus: 2.3.0
  - files_automatedtagging: 1.5.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.2
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - user_ldap: 1.5.0
  - user_usage_report: 1.1.2
  - workflowengine: 1.5.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": "help\/skeletondirectory",
        "logfile": "\/var\/www\/nextcloud\/log\/nextcloud.log",
        "log_rotate_size": 104857600,
        "logtimezone": "Asia\/Taipei",
        "logdateformat": "Y-m-d H:i:s",
        "loglevel": 1,
        "has_internet_connection": false,
        "lost_password_link": "disabled",
        "remember_login_cookie_lifetime": 0,
        "login_form_autocomplete": false,
        "knowledgebaseenabled": false,
        "simpleSignUpLink.shown": false,
        "trashbin_retention_obligation": "auto, D7",
        "theme": "",
        "overwriteprotocol": "https",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        }
    }
}
```

### Client configuration
**Browser:**: chrome

**Operating system:**: Windows

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"xFueI2yTlGk61RINcg65","level":3,"time":"2020-05-26T10:30:08+08:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Return value of OCA\\Files_Antivirus\\BackgroundJob\\BackgroundScanner::scanOneFile() must be an instance of OCA\\Files_Antivirus\\BackgroundJob\\void, none returned","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_antivirus/lib/BackgroundJob/BackgroundScanner.php","line":114,"function":"scanOneFile","class":"OCA\\Files_Antivirus\\BackgroundJob\\BackgroundScanner","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\Files_Antivirus\\BackgroundJob\\BackgroundScanner","type":"->","args":[null]},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/files_antivirus/lib/BackgroundJob/BackgroundScanner.php","Line":253,"CustomMessage":"--"},"userAgent":"--","version":"15.0.7.0","displayname":"--","id":"5ecc858671a55"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by louis378** [comment] 2020-07-22 07:33
Anyone here?

**Comment by kesselb** [comment] 2021-08-19 07:20
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by kesselb** 2021-08-19 07:20 UTC
